trigger:
- main
- releases/*

pr:
- main
- releases/*

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: |
      mkdir "$(Build.ArtifactStagingDirectory)/whvp-sys"
    displayName: Prep Build
  - script: |
      cargo build --manifest-path whvp-sys/Cargo.toml --lib
    displayName: Build 
  - task: CopyFiles@2
    inputs:
      sourceFolder: whvp-sys
      targetFolder: $(Build.ArtifactStagingDirectory)\whvp-sys
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: whvp-sys-x64-win
